Repository juntofoundation/junto-mobile, pull requests merged in 2020-05, with the labels that each got.

#609 Update gradle version
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
Labels: bug

#607 S3 content update
  lib/backend/services/auth_service.dart
  lib/backend/services/expression_provider.dart
  lib/hive_keys.dart
  lib/utils/junto_http.dart
Labels: bug

#622 Move function out of build
  lib/screens/expression_open/expressions/audio_open.dart
Labels: bug

#634 Added Image Compression
  lib/screens/create/create_templates/photo.dart
  lib/utils/time_logger.dart
  lib/utils/utils.dart
  lib/widgets/image_cropper.dart
  pubspec.yaml
Labels: Caching, High Priority, bug

#663 Use custom cache manager
  lib/screens/expression_open/expressions/audio_open.dart
  lib/screens/expression_open/expressions/event_open.dart
  lib/screens/expression_open/expressions/photo_open.dart
  lib/screens/groups/spheres/sphere_open/sphere_open.dart
  lib/screens/notifications/notification_types/previews/photo_preview.dart
  lib/utils/cache_manager.dart
  lib/widgets/avatars/group_avatar.dart
  lib/widgets/avatars/member_avatar.dart
  lib/widgets/image_wrapper.dart
  lib/widgets/member_widgets/background_photo.dart
  lib/widgets/member_widgets/profile_picture_full.dart
  lib/widgets/previews/expression_preview/single_column_preview/single_column_expression_preview_types/event.dart
  lib/widgets/previews/expression_preview/single_column_preview/single_column_expression_preview_types/photo.dart
  lib/widgets/previews/expression_preview/two_column_preview/two_column_expression_preview_types/event.dart
  lib/widgets/previews/expression_preview/two_column_preview/two_column_expression_preview_types/photo.dart
  lib/widgets/previews/sphere_preview/sphere_preview.dart
  pubspec.yaml
Labels: Suggestion

#683 Fixes various performance issues
  lib/backend/user_data_provider.dart
  lib/screens/collective/perspectives/collective_populated_list.dart
  lib/screens/expression_open/expressions/photo_open.dart
  lib/widgets/custom_feeds/custom_listview.dart
  lib/widgets/custom_feeds/group_expressions.dart
  lib/widgets/custom_feeds/single_listview.dart
  lib/widgets/custom_feeds/user_expressions.dart
  lib/widgets/image_wrapper.dart
  lib/widgets/previews/expression_preview/single_column_preview/single_column_expression_preview.dart
  lib/widgets/previews/expression_preview/single_column_preview/single_column_expression_preview_types/photo.dart
  lib/widgets/previews/expression_preview/two_column_preview/two_column_expression_preview.dart
  lib/widgets/previews/expression_preview/two_column_preview/two_column_expression_preview_types/audio.dart
  lib/widgets/previews/expression_preview/two_column_preview/two_column_expression_preview_types/photo.dart
  pubspec.yaml
Labels: Caching, High Priority, Performance, bug

#690 Reland performance fixes
  ios/Flutter/.last_build_id
  lib/app/custom_icons.dart
  lib/app/expressions.dart
  lib/backend/mock/mock_expression.dart
  lib/backend/repositories/user_repo.dart
  lib/generated/intl/messages_de.dart
  lib/generated/intl/messages_pl.dart
  lib/generated/intl/messages_pt.dart
  lib/generated/l10n.dart
  lib/hive_keys.dart
  lib/l10n/intl_de.arb
  lib/l10n/intl_en.arb
  lib/l10n/intl_pl.arb
  lib/l10n/intl_pt.arb
  lib/screens/collective/perspectives/collective_populated_list.dart
  lib/screens/collective/perspectives/expression_feed.dart
  lib/screens/collective/perspectives/perspectives_header.dart
  lib/screens/create/create_templates/audio_service.dart
  lib/screens/create/create_templates/widgets/audio_photo_options.dart
  lib/screens/den/den.dart
  lib/screens/expression_open/expressions/audio_open.dart
  lib/screens/expression_open/expressions/event_open.dart
  lib/screens/groups/spheres/create_sphere/create_sphere.dart
  lib/screens/groups/spheres/create_sphere/create_sphere_page_two.dart
  lib/screens/groups/spheres/sphere_open/sphere_open.dart
  lib/screens/groups/spheres/sphere_open/sphere_open_about.dart
  lib/screens/groups/spheres/sphere_open/sphere_open_appbar.dart
  lib/screens/groups/spheres/spheres.dart
  lib/screens/groups/spheres/spheres_search.dart
  lib/screens/lotus/lotus.dart
  lib/screens/notifications/notification_types/previews/dynamic_preview.dart
  lib/screens/notifications/notification_types/previews/photo_preview.dart
  lib/screens/notifications/views/expression_view.dart
  lib/screens/notifications/views/relations_view.dart
  lib/screens/packs/pack_open/pack_tabs.dart
  lib/screens/packs/packs_list.dart
  lib/screens/welcome/widgets/sign_up_text_field_wrapper.dart
  lib/screens/welcome/widgets/welcome_background.dart
  lib/utils/time_logger.dart
  lib/widgets/appbar/collective_appbar.dart
  lib/widgets/appbar/notifications_lunar_icon.dart
  lib/widgets/avatars/member_avatar.dart
  lib/widgets/background/background_theme.dart
  lib/widgets/custom_feeds/custom_listview.dart
  lib/widgets/custom_feeds/group_expressions.dart
  lib/widgets/custom_feeds/single_listview.dart
  lib/widgets/custom_feeds/user_expressions.dart
  lib/widgets/dialogs/single_action_dialog.dart
  lib/widgets/drawer/widgets/widgets.dart
  lib/widgets/image_cropper.dart
  lib/widgets/previews/channel_preview.dart
  lib/widgets/previews/expression_preview/single_column_preview/single_column_expression_preview_types/photo.dart
  lib/widgets/tab_bar.dart
  pubspec.yaml
Labels: bug

#711 Delete Expressions
  lib/screens/collective/bloc/collective_bloc.dart
  lib/screens/collective/bloc/collective_event.dart
  lib/screens/collective/perspectives/collective_populated_list.dart
  lib/screens/collective/perspectives/expression_feed.dart
  lib/screens/collective/perspectives/perspective_item.dart
  lib/screens/den/bloc/den_bloc.dart
  lib/screens/den/bloc/den_event.dart
  lib/screens/den/den.dart
  lib/screens/expression_open/expression_open.dart
  lib/screens/expression_open/expression_open_top.dart
  lib/screens/groups/spheres/sphere_open/action_items/creator/action_items.dart
  lib/screens/member/member.dart
  lib/screens/notifications/widgets/notification_tile.dart
  lib/screens/packs/pack_open/pack_open_action_items.dart
  lib/screens/packs/packs_bloc/pack_bloc.dart
  lib/screens/packs/packs_bloc/pack_event.dart
  lib/widgets/action_items/expression_action_items.dart
  lib/widgets/custom_feeds/custom_listview.dart
  lib/widgets/custom_feeds/group_expressions.dart
  lib/widgets/custom_feeds/single_listview.dart
  lib/widgets/custom_feeds/user_expressions.dart
  lib/widgets/dialogs/confirm_dialog.dart
  lib/widgets/dialogs/single_action_dialog.dart
  lib/widgets/previews/expression_preview/expression_preview_bottom.dart
  lib/widgets/previews/expression_preview/single_column_preview/single_column_expression_preview.dart
  lib/widgets/previews/expression_preview/two_column_preview/two_column_expression_preview.dart
Labels: Caching, High Priority, bug

#720 Inconsistent theme
  lib/backend/backend.dart
  lib/backend/repositories/auth_repo.dart
Labels: High Priority, bug

#750 Closes #733
  lib/screens/create/create_actions/create_actions.dart
Labels: bug
